[project]
name = "broken-britain"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "google-generativeai>=0.8.5",
    "markitdown[all]>=0.1.1",
    "pyproj>=3.7.1",
]
